# Generated by Django 3.2 on 2021-05-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedetails',
            name='prf_number',
            field=models.CharField(max_length=64, null=True, verbose_name='PRF Number'),
        ),
        migrations.AlterField(
            model_name='purchaserequirement',
            name='prf_number',
            field=models.CharField(max_length=64, null=True, verbose_name='PRF Number'),
        ),
        migrations.AlterField(
            model_name='quotationdetails',
            name='prf_number',
            field=models.CharField(max_length=64, null=True, verbose_name='PRF Number'),
        ),
        migrations.AlterField(
            model_name='quotationlinedetails',
            name='prf_number',
            field=models.CharField(max_length=64, null=True, verbose_name='PRF Number'),
        ),
    ]
