# Generated by Django 3.2 on 2021-05-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_uploadfiles_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequirement',
            name='finalized_vendor',
            field=models.CharField(max_length=255, null=True, verbose_name='Finalized Vendor'),
        ),
    ]
