# Generated by Django 3.2 on 2021-05-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationdetails',
            name='VendorFile_name',
            field=models.TextField(null=True, verbose_name='Vendor File Name'),
        ),
        migrations.AddField(
            model_name='quotationlinedetails',
            name='quotationfile_name',
            field=models.TextField(null=True, verbose_name='Quotation File Name'),
        ),
        migrations.AlterField(
            model_name='purchaserequirement',
            name='po_status',
            field=models.CharField(max_length=128, null=True, verbose_name='PO Status'),
        ),
    ]
