# Generated by Django 3.2 on 2021-05-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_auto_20210512_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationlinedetails',
            name='vendor_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Vendor Name'),
        ),
    ]
