# Generated by Django 3.2 on 2021-05-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_quotationlinedetails_vendor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationlinedetails',
            name='quotationfile_name',
        ),
        migrations.AddField(
            model_name='quotationdetails',
            name='quotationfile_name',
            field=models.TextField(null=True, verbose_name='Quotation File Name'),
        ),
    ]
