# Generated by Django 3.2 on 2021-05-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_auto_20210512_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequirement',
            name='is_approver_approved',
            field=models.IntegerField(default=False, verbose_name='Is Approver Approved ?'),
        ),
        migrations.AlterField(
            model_name='purchaserequirement',
            name='is_dept_head_approved',
            field=models.IntegerField(default=False, verbose_name='Is Department Head Approved ?'),
        ),
        migrations.AlterField(
            model_name='purchaserequirement',
            name='is_finance_approved',
            field=models.IntegerField(default=False, verbose_name='Is Finance Approved ?'),
        ),
        migrations.AlterField(
            model_name='purchaserequirement',
            name='is_p2p_approved',
            field=models.IntegerField(default=False, verbose_name='Is P2P Approved ?'),
        ),
        migrations.AlterField(
            model_name='purchaserequirement',
            name='is_processed',
            field=models.IntegerField(default=False, verbose_name='Is Processed ?'),
        ),
    ]
