# Generated by Django 3.2 on 2021-05-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0012_auto_20210517_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationdetails',
            name='mail_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Mail Id'),
        ),
    ]
