# Generated by Django 3.2 on 2021-05-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0016_vendorfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequirement',
            name='VendorFile_name',
            field=models.TextField(null=True, verbose_name='Vendor File Name'),
        ),
        migrations.AddField(
            model_name='purchaserequirement',
            name='approver_department',
            field=models.CharField(max_length=255, null=True, verbose_name='Approver Department'),
        ),
        migrations.AddField(
            model_name='purchaserequirement',
            name='approver_mailid',
            field=models.TextField(null=True, verbose_name='Approver Mail Id'),
        ),
        migrations.AddField(
            model_name='purchaserequirement',
            name='approver_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Approver Name'),
        ),
        migrations.AddField(
            model_name='purchaserequirement',
            name='vendor_selection_reason',
            field=models.TextField(null=True, verbose_name='Vendor Selection Reason'),
        ),
    ]
