# Generated by Django 3.2 on 2021-05-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0017_auto_20210521_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorfiles',
            name='quotation_details',
        ),
    ]
