# Generated by Django 3.2 on 2021-05-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0018_remove_vendorfiles_quotation_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, null=True, verbose_name='User Name')),
                ('mail_id', models.TextField(null=True, verbose_name='Mail Id')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='Password')),
                ('department', models.CharField(max_length=64, null=True, verbose_name='Department')),
                ('user_id', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
            ],
            options={
                'db_table': 'mail_credentials',
            },
        ),
    ]
