# Generated by Django 3.2 on 2021-06-06 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0019_mailcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcredentials',
            name='created_by',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='User Id'),
        ),
        migrations.AddField(
            model_name='mailcredentials',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='mailcredentials',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active ?'),
        ),
    ]
